### ISSUE TITLE
Scene処理系と描写処理系をメインスレッドに統合

### ISSUE THREAD

**Issue by PastFantasy1640** [musou1500/jubeon2#17]
お互いのデータに関してスレッドセーフ対策をするのが非常に高コスト。処理、描画、と分けたほうが楽そう。
というわけでスレッドを統合する

**Comment by PastFantasy1640** [comment]
#19 プルリクエストを出しました。

**Comment by musou1500** [comment]
プルリクエストがマージされたのでクローズします...
