### ISSUE TITLE
codecvtヘッダが見つからない

### ISSUE THREAD

**Issue by PastFantasy1640** [musou1500/jubeon2#28]
gcc 4.9.2ですが表題の用にエラーが出てました…
いろいろ調べてみたのですが、なんとも、うん

**Comment by musou1500** [comment]
codecvtやthreadはC++11に含まれた機能ですが、実装されていないライブラリもあります。
標準クラスの実装には`libc++`や`libstdc++`がありますが、どちらをお使いでしょうか？

**Comment by PastFantasy1640** [comment]
CMakeListにstd=c++11のみを追加して指定してますが…何か追加でライブラリ表記をする必要があるみたい…？
同じようにコマンドオプションでstdlib=libc++と追記したらcmakeが通らなくてアレェって感じでした、、多分根本的に何か間違ってるのかも

**Comment by musou1500** [comment]
なるほど…CMakeLists.txt見せてもらってもいいですか？

2016/08/14 午前9:33 "PastFantasy1640" <notifications@github.com>:

**Comment by PastFantasy1640** [comment]
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
この一行をset_project？の前に追加しただけです…だから特にライブラリとかは…指定してないんですけど

**Comment by musou1500** [comment]
Debian環境用意して試します…
余裕があればプルリク投げますね

**Comment by PastFantasy1640** [comment]
自分がgccでのエラーを削っていってる途中のverをあげるので、しばしお待ちを…

**Comment by PastFantasy1640** [comment]
https://github.com/PastFantasy1640/jubeon/tree/fix/all_comment_to_ENGLISH
ここに上げてみました
この他にもエラーがあったのですが、それらはぼちぼち修正しつつ…。
あとはcodecvtがどうにかなればコンパイルだけは通るようになるかと思います。

**Comment by musou1500** [comment]
threadクラスは大丈夫そうですか？
以前ためした時、一部サポートされていなかったので...

**Comment by musou1500** [comment]
ちなみに、コメントを英語に修正して回っているのは、エンコーディングを考慮してのことでしょうか？

**Comment by PastFantasy1640** [comment]
大丈夫そうでしたよ
途中でてましたけどincludeしてなかっただけとかでした
threadよりResourceManagerのエラーがちょっとよくわからんです。-fpermissiveオプションでスルーできてますが…。

英語にしてるのはエンコードのため…だけど英語に直すのだるすぎます。しなくても良かったりします？

**Comment by musou1500** [comment]
目的の環境で動けば良いので...
cp932で押し通すか、
utf8を使うなら、clang with microsoft codegenに含まれているclangバイナリを使う手があります。

**Comment by musou1500** [comment]
まとめると、「後回しにしても良さそう」です。

**Comment by PastFantasy1640** [comment]
了解です、そうしましょう

**Comment by musou1500** [comment]
codecvtヘッダが見つからない問題、再現できないですね...

**Comment by PastFantasy1640** [comment]
あれぇ、、、
gccのバージョンとか関係あったりしますかね…。少し前のubuntu使ってるもので、

gccでコンパイル通りました？

**Comment by musou1500** [comment]
いまちょっと別の問題が出てまして...
ResourceManagerの特殊化周りですね

**Comment by PastFantasy1640** [comment]
ですよね…名前空間がなんたら〜って
自分の時も解決できなくて-fpermissive(でしたっけ)オプションで後回しにしてました

**Comment by musou1500** [comment]
割とお手上げ感あるぞ...

**Comment by PastFantasy1640** [comment]
ResourceManagerは解決しました。プルリクエスト投げています。
https://github.com/PastFantasy1640/jubeon/pull/5

**Comment by PastFantasy1640** [comment]
しかしやはりcodecvtに関してはエラーが消えません
`
[ 59%] Building CXX object CMakeFiles/jubeon.dir/src/Jmemo2/Parser.cpp.o
/home/white/jubeon/jubeon/src/Jmemo2/Parser.cpp: In member function ‘void Jmemo2::Parser::initWithString(std::string)’:
/home/white/jubeon/jubeon/src/Jmemo2/Parser.cpp:20:5: error: ‘wstring_convert’ was not declared in this scope
     wstring_convert<codecvt_utf8<wchar_t>, wchar_t> cv;
     ^
/home/white/jubeon/jubeon/src/Jmemo2/Parser.cpp:20:21: error: ‘codecvt_utf8’ was not declared in this scope
     wstring_convert<codecvt_utf8<wchar_t>, wchar_t> cv;
                     ^
/home/white/jubeon/jubeon/src/Jmemo2/Parser.cpp:20:34: error: expected primary-expression before ‘wchar_t’
     wstring_convert<codecvt_utf8<wchar_t>, wchar_t> cv;
                                  ^
/home/white/jubeon/jubeon/src/Jmemo2/Parser.cpp:23:27: error: ‘cv’ was not declared in this scope
     _lexer.initWithString(cv.from_bytes(source));
                           ^
make[2]: *** [CMakeFiles/jubeon.dir/src/Jmemo2/Parser.cpp.o] エラー 1
make[1]: *** [CMakeFiles/jubeon.dir/all] エラー 2
make: *** [all] エラー 2
`

**Comment by musou1500** [comment]
g++のバージョンを教えてください。

...もしかしてgcc?

**Comment by PastFantasy1640** [comment]
こんなかんじです。
```
$ gcc --version
gcc (Ubuntu 4.9.3-8ubuntu2~14.04) 4.9.3
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ g++ --version
g++ (Ubuntu 4.9.3-8ubuntu2~14.04) 4.9.3
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

$ 
```

**Comment by PastFantasy1640** [comment]
もしかしてこれが問題だったりしますかね、
どうやらglibcはインストールされてないみたいです
```
$ rpm -q glibc
パッケージ glibc はインストールされていません。
```

**Comment by musou1500** [comment]
バージョンっぽいですね。
```
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.2) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by musou1500** [comment]
バージョンっぽいですね...
```
i A libstdc++-5-dev                                     - GNU 標準 C++ ライブラリ v3 (開発用ファイル)
```
```
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.2) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by PastFantasy1640** [comment]
バージョンを上げてみました。5.4で全てのコンパイル通りました！
あとはなんかpthreadのリンクエラーが出てますが、じき直ると思います。
ありがとうございました
